// Code generated by command: go run asm.go -pkg gf16 -out gf16/gf16_avx2.s -stubs gf16/stub.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func MulByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)
// Requires: AVX, AVX2
TEXT ·MulByteSliceLE_AVX2(SB), $0-56
	MOVQ           tables+0(FP), AX
	MOVQ           in_base+8(FP), CX
	MOVQ           in_len+16(FP), DX
	MOVQ           out_base+32(FP), BX
	VBROADCASTI128 (AX), Y0
	VBROADCASTI128 16(AX), Y1
	VBROADCASTI128 32(AX), Y2
	VBROADCASTI128 48(AX), Y3
	VBROADCASTI128 64(AX), Y4
	VBROADCASTI128 80(AX), Y5
	VBROADCASTI128 96(AX), Y6
	VBROADCASTI128 112(AX), Y7
	VMOVUPD        mul_mask_avx2<>+0(SB), Y8
	VMOVUPD        conv_mask_avx2<>+0(SB), Y9
	MOVQ           DX, AX
	SHRQ           $0x06, AX

loop:
	CMPQ       AX, $0x00
	JE         done
	VMOVUPD    (CX), Y11
	VMOVUPD    32(CX), Y10
	VMOVDQA    Y10, Y12
	VPSRLW     $0x08, Y10, Y10
	VPAND      Y9, Y12, Y12
	VMOVDQA    Y11, Y13
	VPSRLW     $0x08, Y11, Y11
	VPAND      Y9, Y13, Y13
	VPACKUSWB  Y11, Y10, Y10
	VPACKUSWB  Y13, Y12, Y12
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y0, Y11
	VPSHUFB    Y14, Y11, Y11
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y1, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y2, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y3, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y4, Y13
	VPSHUFB    Y14, Y13, Y13
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y5, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y6, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y7, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y11, Y10
	VPUNPCKHBW Y13, Y10, Y10
	VPUNPCKLBW Y13, Y11, Y11
	VMOVUPD    Y10, (BX)
	VMOVUPD    Y11, 32(BX)
	ADDQ       $0x40, CX
	ADDQ       $0x40, BX
	DECQ       AX
	JMP        loop

done:
	VZEROUPPER
	RET

DATA mul_mask_avx2<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+16(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+24(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL mul_mask_avx2<>(SB), RODATA|NOPTR, $32

DATA conv_mask_avx2<>+0(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+8(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+16(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+24(SB)/8, $0x00ff00ff00ff00ff
GLOBL conv_mask_avx2<>(SB), RODATA|NOPTR, $32

// func MulAndAddByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)
// Requires: AVX, AVX2
TEXT ·MulAndAddByteSliceLE_AVX2(SB), $0-56
	MOVQ           tables+0(FP), AX
	MOVQ           in_base+8(FP), CX
	MOVQ           in_len+16(FP), DX
	MOVQ           out_base+32(FP), BX
	VBROADCASTI128 (AX), Y0
	VBROADCASTI128 16(AX), Y1
	VBROADCASTI128 32(AX), Y2
	VBROADCASTI128 48(AX), Y3
	VBROADCASTI128 64(AX), Y4
	VBROADCASTI128 80(AX), Y5
	VBROADCASTI128 96(AX), Y6
	VBROADCASTI128 112(AX), Y7
	VMOVUPD        mul_mask_avx2_add<>+0(SB), Y8
	VMOVUPD        conv_mask_avx2_add<>+0(SB), Y9
	MOVQ           DX, AX
	SHRQ           $0x06, AX

loop:
	CMPQ       AX, $0x00
	JE         done
	VMOVUPD    (CX), Y11
	VMOVUPD    32(CX), Y10
	VMOVDQA    Y10, Y12
	VPSRLW     $0x08, Y10, Y10
	VPAND      Y9, Y12, Y12
	VMOVDQA    Y11, Y13
	VPSRLW     $0x08, Y11, Y11
	VPAND      Y9, Y13, Y13
	VPACKUSWB  Y11, Y10, Y10
	VPACKUSWB  Y13, Y12, Y12
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y0, Y11
	VPSHUFB    Y14, Y11, Y11
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y1, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y2, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y3, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y4, Y13
	VPSHUFB    Y14, Y13, Y13
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y5, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y6, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y7, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y11, Y10
	VPUNPCKHBW Y13, Y10, Y10
	VPUNPCKLBW Y13, Y11, Y11
	VMOVUPD    (BX), Y12
	VMOVUPD    32(BX), Y13
	VPXOR      Y12, Y10, Y10
	VPXOR      Y13, Y11, Y11
	VMOVUPD    Y10, (BX)
	VMOVUPD    Y11, 32(BX)
	ADDQ       $0x40, CX
	ADDQ       $0x40, BX
	DECQ       AX
	JMP        loop

done:
	VZEROUPPER
	RET

DATA mul_mask_avx2_add<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+16(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+24(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL mul_mask_avx2_add<>(SB), RODATA|NOPTR, $32

DATA conv_mask_avx2_add<>+0(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+8(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+16(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+24(SB)/8, $0x00ff00ff00ff00ff
GLOBL conv_mask_avx2_add<>(SB), RODATA|NOPTR, $32
