// Code generated by command: go run asm.go -pkg gf16 -out gf16_avx2.s -stubs stub.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func MulByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)
// Requires: AVX, AVX2
TEXT ·MulByteSliceLE_AVX2(SB), $0-56
	MOVQ           tables+0(FP), AX
	MOVQ           in_base+8(FP), CX
	MOVQ           in_len+16(FP), DX
	MOVQ           out_base+32(FP), BX
	VBROADCASTI128 (AX), Y0
	VBROADCASTI128 16(AX), Y1
	VBROADCASTI128 32(AX), Y2
	VBROADCASTI128 48(AX), Y3
	VBROADCASTI128 64(AX), Y4
	VBROADCASTI128 80(AX), Y5
	VBROADCASTI128 96(AX), Y6
	VBROADCASTI128 112(AX), Y7
	VMOVUPD        mul_mask_avx2<>+0(SB), Y8
	VMOVUPD        conv_mask_avx2<>+0(SB), Y9
	MOVQ           DX, AX
	SHRQ           $0x06, AX

loop:
	CMPQ       AX, $0x00
	JE         done
	VMOVUPD    (CX), Y11
	VMOVUPD    32(CX), Y10
	VMOVDQA    Y10, Y12
	VPSRLW     $0x08, Y10, Y10
	VPAND      Y9, Y12, Y12
	VMOVDQA    Y11, Y13
	VPSRLW     $0x08, Y11, Y11
	VPAND      Y9, Y13, Y13
	VPACKUSWB  Y11, Y10, Y10
	VPACKUSWB  Y13, Y12, Y12
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y0, Y11
	VPSHUFB    Y14, Y11, Y11
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y1, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y2, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y3, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y4, Y13
	VPSHUFB    Y14, Y13, Y13
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y5, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y6, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y7, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y11, Y10
	VPUNPCKHBW Y13, Y10, Y10
	VPUNPCKLBW Y13, Y11, Y11
	VMOVUPD    Y10, (BX)
	VMOVUPD    Y11, 32(BX)
	ADDQ       $0x40, CX
	ADDQ       $0x40, BX
	DECQ       AX
	JMP        loop

done:
	VZEROUPPER
	RET

DATA mul_mask_avx2<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+16(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2<>+24(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL mul_mask_avx2<>(SB), RODATA|NOPTR, $32

DATA conv_mask_avx2<>+0(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+8(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+16(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2<>+24(SB)/8, $0x00ff00ff00ff00ff
GLOBL conv_mask_avx2<>(SB), RODATA|NOPTR, $32

// func MulAndAddByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)
// Requires: AVX, AVX2
TEXT ·MulAndAddByteSliceLE_AVX2(SB), $0-56
	MOVQ           tables+0(FP), AX
	MOVQ           in_base+8(FP), CX
	MOVQ           in_len+16(FP), DX
	MOVQ           out_base+32(FP), BX
	VBROADCASTI128 (AX), Y0
	VBROADCASTI128 16(AX), Y1
	VBROADCASTI128 32(AX), Y2
	VBROADCASTI128 48(AX), Y3
	VBROADCASTI128 64(AX), Y4
	VBROADCASTI128 80(AX), Y5
	VBROADCASTI128 96(AX), Y6
	VBROADCASTI128 112(AX), Y7
	VMOVUPD        mul_mask_avx2_add<>+0(SB), Y8
	VMOVUPD        conv_mask_avx2_add<>+0(SB), Y9
	MOVQ           DX, AX
	SHRQ           $0x06, AX

loop:
	CMPQ       AX, $0x00
	JE         done
	VMOVUPD    (CX), Y11
	VMOVUPD    32(CX), Y10
	VMOVDQA    Y10, Y12
	VPSRLW     $0x08, Y10, Y10
	VPAND      Y9, Y12, Y12
	VMOVDQA    Y11, Y13
	VPSRLW     $0x08, Y11, Y11
	VPAND      Y9, Y13, Y13
	VPACKUSWB  Y11, Y10, Y10
	VPACKUSWB  Y13, Y12, Y12
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y0, Y11
	VPSHUFB    Y14, Y11, Y11
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y1, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y2, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y3, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y11, Y11
	VMOVDQA    Y12, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y4, Y13
	VPSHUFB    Y14, Y13, Y13
	VMOVDQA    Y12, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y5, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y6, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y10, Y14
	VPSRLW     $0x04, Y14, Y14
	VPAND      Y8, Y14, Y14
	VMOVDQA    Y7, Y15
	VPSHUFB    Y14, Y15, Y15
	VPXOR      Y15, Y13, Y13
	VMOVDQA    Y11, Y10
	VPUNPCKHBW Y13, Y10, Y10
	VPUNPCKLBW Y13, Y11, Y11
	VMOVUPD    (BX), Y12
	VMOVUPD    32(BX), Y13
	VPXOR      Y12, Y10, Y10
	VPXOR      Y13, Y11, Y11
	VMOVUPD    Y10, (BX)
	VMOVUPD    Y11, 32(BX)
	ADDQ       $0x40, CX
	ADDQ       $0x40, BX
	DECQ       AX
	JMP        loop

done:
	VZEROUPPER
	RET

DATA mul_mask_avx2_add<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+16(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA mul_mask_avx2_add<>+24(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL mul_mask_avx2_add<>(SB), RODATA|NOPTR, $32

DATA conv_mask_avx2_add<>+0(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+8(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+16(SB)/8, $0x00ff00ff00ff00ff
DATA conv_mask_avx2_add<>+24(SB)/8, $0x00ff00ff00ff00ff
GLOBL conv_mask_avx2_add<>(SB), RODATA|NOPTR, $32

DATA gfni_lo_mask<>+0(SB)/8, $0x00ff00ff00ff00ff
DATA gfni_lo_mask<>+8(SB)/8, $0x00ff00ff00ff00ff
DATA gfni_lo_mask<>+16(SB)/8, $0x00ff00ff00ff00ff
DATA gfni_lo_mask<>+24(SB)/8, $0x00ff00ff00ff00ff
GLOBL gfni_lo_mask<>(SB), RODATA|NOPTR, $32

DATA gfni_hi_mask<>+0(SB)/8, $0xff00ff00ff00ff00
DATA gfni_hi_mask<>+8(SB)/8, $0xff00ff00ff00ff00
DATA gfni_hi_mask<>+16(SB)/8, $0xff00ff00ff00ff00
DATA gfni_hi_mask<>+24(SB)/8, $0xff00ff00ff00ff00
GLOBL gfni_hi_mask<>(SB), RODATA|NOPTR, $32

// func MulByteSliceLE_GFNI(matrices *[4]uint64, in []byte, out []byte)
// Requires: AVX, AVX2, GFNI
TEXT ·MulByteSliceLE_GFNI(SB), NOSPLIT, $0-56
	MOVQ         matrices+0(FP), AX
	MOVQ         in_base+8(FP), CX
	MOVQ         in_len+16(FP), DX
	MOVQ         out_base+32(FP), BX
	VPBROADCASTQ (AX), Y0
	VPBROADCASTQ 8(AX), Y1
	VPBROADCASTQ 16(AX), Y2
	VPBROADCASTQ 24(AX), Y3
	VMOVDQU      gfni_lo_mask<>+0(SB), Y4
	VMOVDQU      gfni_hi_mask<>+0(SB), Y5
	MOVQ         DX, AX
	SHRQ         $0x05, AX

MulByteSliceLE_GFNI_loop:
	CMPQ           AX, $0x00
	JE             MulByteSliceLE_GFNI_done
	VMOVDQU        (CX), Y6
	VGF2P8AFFINEQB $0x00, Y0, Y6, Y7
	VGF2P8AFFINEQB $0x00, Y1, Y6, Y8
	VGF2P8AFFINEQB $0x00, Y2, Y6, Y9
	VGF2P8AFFINEQB $0x00, Y3, Y6, Y6
	VPSRLW         $0x08, Y8, Y8
	VPSLLW         $0x08, Y9, Y9
	VPXOR          Y7, Y8, Y8
	VPXOR          Y6, Y9, Y9
	VPAND          Y4, Y8, Y8
	VPAND          Y5, Y9, Y9
	VPOR           Y8, Y9, Y6
	VMOVDQU        Y6, (BX)
	ADDQ           $0x20, CX
	ADDQ           $0x20, BX
	DECQ           AX
	JMP            MulByteSliceLE_GFNI_loop

MulByteSliceLE_GFNI_done:
	VZEROUPPER
	RET

// func MulAndAddByteSliceLE_GFNI(matrices *[4]uint64, in []byte, out []byte)
// Requires: AVX, AVX2, GFNI
TEXT ·MulAndAddByteSliceLE_GFNI(SB), NOSPLIT, $0-56
	MOVQ         matrices+0(FP), AX
	MOVQ         in_base+8(FP), CX
	MOVQ         in_len+16(FP), DX
	MOVQ         out_base+32(FP), BX
	VPBROADCASTQ (AX), Y0
	VPBROADCASTQ 8(AX), Y1
	VPBROADCASTQ 16(AX), Y2
	VPBROADCASTQ 24(AX), Y3
	VMOVDQU      gfni_lo_mask<>+0(SB), Y4
	VMOVDQU      gfni_hi_mask<>+0(SB), Y5
	MOVQ         DX, AX
	SHRQ         $0x05, AX

MulAndAddByteSliceLE_GFNI_loop:
	CMPQ           AX, $0x00
	JE             MulAndAddByteSliceLE_GFNI_done
	VMOVDQU        (CX), Y6
	VGF2P8AFFINEQB $0x00, Y0, Y6, Y7
	VGF2P8AFFINEQB $0x00, Y1, Y6, Y8
	VGF2P8AFFINEQB $0x00, Y2, Y6, Y9
	VGF2P8AFFINEQB $0x00, Y3, Y6, Y6
	VPSRLW         $0x08, Y8, Y8
	VPSLLW         $0x08, Y9, Y9
	VPXOR          Y7, Y8, Y8
	VPXOR          Y6, Y9, Y9
	VPAND          Y4, Y8, Y8
	VPAND          Y5, Y9, Y9
	VPOR           Y8, Y9, Y6
	VMOVDQU        (BX), Y7
	VPXOR          Y7, Y6, Y6
	VMOVDQU        Y6, (BX)
	ADDQ           $0x20, CX
	ADDQ           $0x20, BX
	DECQ           AX
	JMP            MulAndAddByteSliceLE_GFNI_loop

MulAndAddByteSliceLE_GFNI_done:
	VZEROUPPER
	RET
