// Code generated by command: go run asm.go -out gf16/gf16_avx2.s -stubs gf16/stub.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func MulByteSliceLE_AVX2(tables *[4][32]byte, in []byte, out []byte)
// Requires: AVX, AVX2
TEXT ·MulByteSliceLE_AVX2(SB), $0-56
	MOVQ    tables+0(FP), AX
	MOVQ    in_base+8(FP), CX
	MOVQ    in_len+16(FP), DX
	MOVQ    out_base+32(FP), BX
	VMOVUPD (AX), Y0
	VMOVUPD 32(AX), Y1
	VMOVUPD 64(AX), Y2
	VMOVUPD 96(AX), Y3
	VPXOR   Y4, Y4, Y4
	VMOVUPD nibble_mask<>+0(SB), Y4

loop:
	CMPQ       DX, $0x20
	JL         tail
	VMOVUPD    (CX), Y5
	VANDPS     Y4, Y5, Y6
	VPSHUFB    Y6, Y1, Y7
	VPSHUFB    Y6, Y0, Y8
	VPSRLW     $0x04, Y5, Y6
	VANDPS     Y4, Y6, Y6
	VPSHUFB    Y6, Y3, Y5
	VPSHUFB    Y6, Y2, Y6
	VPXOR      Y5, Y7, Y7
	VPXOR      Y6, Y8, Y8
	VPERM2I128 $0x01, Y7, Y7, Y7
	VPXOR      Y7, Y8, Y8
	VMOVUPD    Y8, (BX)
	ADDQ       $0x20, CX
	ADDQ       $0x20, BX
	SUBQ       $0x20, DX
	JMP        loop

tail:
	VZEROUPPER
	RET

DATA nibble_mask<>+0(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA nibble_mask<>+8(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA nibble_mask<>+16(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA nibble_mask<>+24(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL nibble_mask<>(SB), RODATA|NOPTR, $32
