// Code generated by command: go run asm.go -out gf16/gf16_avx2.s -stubs gf16/stub.go. DO NOT EDIT.

//go:build amd64

package par2engine

// MulByteSliceLE_AVX2 multiplies each 16-bit element in the 'in' slice by a constant
// using AVX2 vector shuffles and the precomputed 4-bit tables, storing the result in 'out'.
func MulByteSliceLE_AVX2(tables *[4][32]byte, in []byte, out []byte)
