// Code generated by command: go run asm.go -pkg gf16 -out gf16/gf16_avx2.s -stubs gf16/stub.go. DO NOT EDIT.

//go:build amd64

package gf16

// MulByteSliceLE_AVX2 multiplies each 16-bit element in 'in' by a constant
// using AVX2 planar repack and 4-bit shuffles, storing the result in 'out'.
// Processes 64 bytes (32 elements) per iteration. len(in) must be a multiple of 64.
func MulByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)

// MulAndAddByteSliceLE_AVX2 multiplies each 16-bit element in 'in' by a constant
// using AVX2 planar repack and 4-bit shuffles, XORing the result into 'out'.
// Processes 64 bytes (32 elements) per iteration. len(in) must be a multiple of 64.
func MulAndAddByteSliceLE_AVX2(tables *[128]byte, in []byte, out []byte)
